FROM python:3.8
COPY requirements.txt /bookapp/requirements.txt
WORKDIR /bookapp
RUN pip3 install -r requirements.txt
copy . /bookapp
#ENTRYPOINT ["python"]
RUN chmod 777 ./startup.sh
CMD ["./startup.sh"]
